### ISSUE TITLE
Installation on Mac OS X

### ISSUE THREAD

**Issue by b1t3s1z3** [epifab/pypoker#5]
Hi there,

Am trying to install this software on my machine, and have managed to work my way past several installation hurdles. I have run into the following error though:

`Traceback (most recent call last):
  File "texasholdem_poker_service.py", line 21, in <module>
    mongo_db = pymongo.MongoClient(mongo_url).get_default_database()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1742, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
`

I've never used Mongo before – how do I "define" what the default database should be? Do I already have a default database? I've been searching on the web but as a newb to this particular software, I'm not entirely sure what to search for. Any help would be greatly appreciated.

**Comment by b1t3s1z3** [comment]
Hi there,

I appear to have resolved the above issue, and appear almost able to use the software, as I have started the server successfully.

But how do I actually launch the game? When I type `python2 client_web.py` into the command line, nothing happens. Is that how I'm supposed to initialize the client?

**Comment by epifab** [comment]
hi, sorry for replying so late.
it's been ages since I last worked on this, but looking at the [Procfile](https://github.com/epifab/pypoker/blob/master/Procfile)  you'll have to start a worker and the web application. you'll also need to have a redis up and running
