### ISSUE TITLE
Update to Python3

### ISSUE THREAD

**Issue by subhajeet2107** [epifab/pypoker#6]
Hi,
While running with Python3 environment i am getting Connection Timed out, what changes do we need to make to run with python3, i can help with this

**Comment by Shivaprasadr** [comment]
Hi is it fixed ?
I need to know if i can work with python3.

**Comment by epifab** [comment]
@Shivaprasadr @subhajeet2107 sorry I hadn't worked on this project for years but in case you're still interested this has now been upgraded to python3
